services:
  review:
    build: ./src
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - minio
    environment:
      - STORAGE_PROVIDER=minio
      # - STORAGE_PROVIDER=aws
      - S3_ENDPOINT=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - S3_REGION=us-east-1
      - S3_BUCKET=reviews
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=review

    # develop:
    #   watch:
    #     - action: sync
    #       path: ./src
    #       target: /app
  mysql:
    image: "mysql:latest"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=review
    volumes:
      - ./data/mysql:/var/lib/mysql
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console UI
    volumes:
      - ./data/minio:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9001" /data
